import { invoke } from "@tauri-apps/api/core";

type CommandArgs = Record<string, unknown>;

export function command<T = unknown>(name: string, args?: CommandArgs) {
  return invoke<T>(name, args ?? {});
}

export const commands = {
  create_matter: (payload: CommandArgs) => command("create_matter", { payload }),
  list_matters: () => command("list_matters"),
  get_matter: (id: string) => command("get_matter", { id }),
  get_matter_profile: (matterId: string) => command("get_matter_profile", { matterId }),
  save_matter_profile: (payload: CommandArgs) => command("save_matter_profile", { payload }),
  list_matter_parties: (matterId: string) => command("list_matter_parties", { matterId }),
  add_matter_party: (payload: CommandArgs) => command("add_matter_party", { payload }),
  update_matter_party: (payload: CommandArgs) => command("update_matter_party", { payload }),
  delete_matter_party: (id: string) => command("delete_matter_party", { id }),
  list_authorities: (matterId: string) => command("list_authorities", { matterId }),
  add_authority: (payload: CommandArgs) => command("add_authority", { payload }),
  update_authority: (payload: CommandArgs) => command("update_authority", { payload }),
  delete_authority: (id: string) => command("delete_authority", { id }),
  ingest_document: (payload: CommandArgs) => command("ingest_document", { payload }),
  list_documents: (matterId: string) => command("list_documents", { matterId }),
  delete_document: (id: string) => command("delete_document", { id }),
  list_document_pages: (documentVersionId: string) => command("list_document_pages", { documentVersionId }),
  get_extracted_text: (documentId: string) => command("get_extracted_text", { documentId }),
  create_fact: (payload: CommandArgs) => command("create_fact", { payload }),
  list_facts: (matterId: string) => command("list_facts", { matterId }),
  delete_fact: (id: string) => command("delete_fact", { id }),
  save_legal_deadline: (payload: CommandArgs) => command("save_legal_deadline", { payload }),
  list_legal_deadlines: (matterId: string) => command("list_legal_deadlines", { matterId }),
  delete_legal_deadline: (id: string) => command("delete_legal_deadline", { id }),
  save_task: (payload: CommandArgs) => command("save_task", { payload }),
  list_tasks: (matterId: string) => command("list_tasks", { matterId }),
  delete_task: (id: string) => command("delete_task", { id }),
  save_waiting_for: (payload: CommandArgs) => command("save_waiting_for", { payload }),
  list_waiting_for: (matterId: string) => command("list_waiting_for", { matterId }),
  close_waiting_for: (id: string) => command("close_waiting_for", { id }),
  save_workstream: (payload: CommandArgs) => command("save_workstream", { payload }),
  list_workstreams: (matterId: string) => command("list_workstreams", { matterId }),
  delete_workstream: (id: string) => command("delete_workstream", { id }),
  create_medical_event: (payload: CommandArgs) => command("create_medical_event", { payload }),
  update_medical_event: (payload: CommandArgs) => command("update_medical_event", { payload }),
  verify_medical_event: (payload: CommandArgs) => command("verify_medical_event", { payload }),
  supersede_medical_event: (payload: CommandArgs) => command("supersede_medical_event", { payload }),
  delete_medical_event: (payload: CommandArgs) => command("delete_medical_event", { payload }),
  list_medical_events: (matterId: string) => command("list_medical_events", { matterId }),
  create_wage_record: (payload: CommandArgs) => command("create_wage_record", { payload }),
  update_wage_record: (payload: CommandArgs) => command("update_wage_record", { payload }),
  verify_wage_record: (payload: CommandArgs) => command("verify_wage_record", { payload }),
  supersede_wage_record: (payload: CommandArgs) => command("supersede_wage_record", { payload }),
  delete_wage_record: (payload: CommandArgs) => command("delete_wage_record", { payload }),
  list_wage_records: (matterId: string) => command("list_wage_records", { matterId }),
  create_liability_fact: (payload: CommandArgs) => command("create_liability_fact", { payload }),
  update_liability_fact: (payload: CommandArgs) => command("update_liability_fact", { payload }),
  verify_liability_fact: (payload: CommandArgs) => command("verify_liability_fact", { payload }),
  supersede_liability_fact: (payload: CommandArgs) => command("supersede_liability_fact", { payload }),
  delete_liability_fact: (payload: CommandArgs) => command("delete_liability_fact", { payload }),
  list_liability_facts: (matterId: string) => command("list_liability_facts", { matterId }),
  list_missing_evidence_matrix: (matterId: string) => command("list_missing_evidence_matrix", { matterId }),
  get_ai_capabilities: (matterId: string) => command("get_ai_capabilities", { matterId }),
  preview_ai_context: (payload: CommandArgs) => command("preview_ai_context", { payload }),
  run_ai_extract_facts: (payload: CommandArgs) => command("run_ai_extract_facts", { payload }),
  list_ai_proposals: (matterId: string) => command("list_ai_proposals", { matterId }),
  approve_ai_proposal: (payload: CommandArgs) => command("approve_ai_proposal", { payload }),
  reject_ai_proposal: (payload: CommandArgs) => command("reject_ai_proposal", { payload }),
  get_case_health: (matterId: string) => command("get_case_health", { matterId }),
  list_insurance_claims: (matterId: string) => command("list_insurance_claims", { matterId }),
  save_insurance_claim: (payload: CommandArgs) => command("save_insurance_claim", { payload }),
  change_insurance_claim_status: (payload: CommandArgs) => command("change_insurance_claim_status", { payload }),
  list_insurance_claim_status_history: (matterId: string, claimId: string) =>
    command("list_insurance_claim_status_history", { matterId, claimId }),
  list_negotiation_events: (matterId: string) => command("list_negotiation_events", { matterId }),
  add_negotiation_event: (payload: CommandArgs) => command("add_negotiation_event", { payload }),
  correct_negotiation_event: (payload: CommandArgs) => command("correct_negotiation_event", { payload }),
  list_negotiation_positions: (matterId: string) => command("list_negotiation_positions", { matterId }),
  add_negotiation_position: (payload: CommandArgs) => command("add_negotiation_position", { payload }),
  correct_negotiation_position: (payload: CommandArgs) => command("correct_negotiation_position", { payload }),
  get_negotiation_snapshot: (matterId: string) => command("get_negotiation_snapshot", { matterId }),
};
