import { invoke } from "@tauri-apps/api/core";

export async function call<T=unknown>(command:string,payload:Record<string,unknown>={}):Promise<T>{
  return invoke<T>(command,{payload});
}

export const commands = {
  get_app_health: (payload:Record<string,unknown>={}) => call("get_app_health",payload),
  get_settings: (payload:Record<string,unknown>={}) => call("get_settings",payload),
  save_settings: (payload:Record<string,unknown>={}) => call("save_settings",payload),
  choose_folder: (payload:Record<string,unknown>={}) => call("choose_folder",payload),
  get_office_root: (payload:Record<string,unknown>={}) => call("get_office_root",payload),
  set_office_root: (payload:Record<string,unknown>={}) => call("set_office_root",payload),
  scan_office_root: (payload:Record<string,unknown>={}) => call("scan_office_root",payload),
  list_scan_runs: (payload:Record<string,unknown>={}) => call("list_scan_runs",payload),
  list_matter_suggestions: (payload:Record<string,unknown>={}) => call("list_matter_suggestions",payload),
  bind_existing_matter: (payload:Record<string,unknown>={}) => call("bind_existing_matter",payload),
  reject_matter_suggestion: (payload:Record<string,unknown>={}) => call("reject_matter_suggestion",payload),
  create_matter: (payload:Record<string,unknown>={}) => call("create_matter",payload),
  list_matters: (payload:Record<string,unknown>={}) => call("list_matters",payload),
  get_matter: (payload:Record<string,unknown>={}) => call("get_matter",payload),
  update_matter: (payload:Record<string,unknown>={}) => call("update_matter",payload),
  set_matter_stage: (payload:Record<string,unknown>={}) => call("set_matter_stage",payload),
  list_documents: (payload:Record<string,unknown>={}) => call("list_documents",payload),
  get_document: (payload:Record<string,unknown>={}) => call("get_document",payload),
  list_document_versions: (payload:Record<string,unknown>={}) => call("list_document_versions",payload),
  open_occurrence: (payload:Record<string,unknown>={}) => call("open_occurrence",payload),
  reveal_occurrence: (payload:Record<string,unknown>={}) => call("reveal_occurrence",payload),
  search_everything: (payload:Record<string,unknown>={}) => call("search_everything",payload),
  hash_pending_files: (payload:Record<string,unknown>={}) => call("hash_pending_files",payload),
  extract_document_text: (payload:Record<string,unknown>={}) => call("extract_document_text",payload),
  get_document_pages: (payload:Record<string,unknown>={}) => call("get_document_pages",payload),
  classify_document_manual: (payload:Record<string,unknown>={}) => call("classify_document_manual",payload),
  list_tasks: (payload:Record<string,unknown>={}) => call("list_tasks",payload),
  create_task: (payload:Record<string,unknown>={}) => call("create_task",payload),
  update_task: (payload:Record<string,unknown>={}) => call("update_task",payload),
  complete_task: (payload:Record<string,unknown>={}) => call("complete_task",payload),
  list_calendar_items: (payload:Record<string,unknown>={}) => call("list_calendar_items",payload),
  create_calendar_item: (payload:Record<string,unknown>={}) => call("create_calendar_item",payload),
  update_calendar_item: (payload:Record<string,unknown>={}) => call("update_calendar_item",payload),
  list_waiting_for: (payload:Record<string,unknown>={}) => call("list_waiting_for",payload),
  save_waiting_for: (payload:Record<string,unknown>={}) => call("save_waiting_for",payload),
  close_waiting_for: (payload:Record<string,unknown>={}) => call("close_waiting_for",payload),
  list_deadlines: (payload:Record<string,unknown>={}) => call("list_deadlines",payload),
  save_manual_deadline: (payload:Record<string,unknown>={}) => call("save_manual_deadline",payload),
  commit_deadline: (payload:Record<string,unknown>={}) => call("commit_deadline",payload),
  supersede_deadline: (payload:Record<string,unknown>={}) => call("supersede_deadline",payload),
  get_ai_settings: (payload:Record<string,unknown>={}) => call("get_ai_settings",payload),
  save_ai_settings: (payload:Record<string,unknown>={}) => call("save_ai_settings",payload),
  test_ai_provider: (payload:Record<string,unknown>={}) => call("test_ai_provider",payload),
  plan_ai_context: (payload:Record<string,unknown>={}) => call("plan_ai_context",payload),
  run_ai_capability: (payload:Record<string,unknown>={}) => call("run_ai_capability",payload),
  get_ai_run: (payload:Record<string,unknown>={}) => call("get_ai_run",payload),
  review_ai_proposal: (payload:Record<string,unknown>={}) => call("review_ai_proposal",payload),
  list_verified_facts: (payload:Record<string,unknown>={}) => call("list_verified_facts",payload),
  verify_fact: (payload:Record<string,unknown>={}) => call("verify_fact",payload),
  invalidate_fact: (payload:Record<string,unknown>={}) => call("invalidate_fact",payload),
  list_damage_calculations: (payload:Record<string,unknown>={}) => call("list_damage_calculations",payload),
  save_damage_calculation: (payload:Record<string,unknown>={}) => call("save_damage_calculation",payload),
  calculate_damage: (payload:Record<string,unknown>={}) => call("calculate_damage",payload),
  lock_damage_calculation: (payload:Record<string,unknown>={}) => call("lock_damage_calculation",payload),
  list_authorities: (payload:Record<string,unknown>={}) => call("list_authorities",payload),
  save_authority: (payload:Record<string,unknown>={}) => call("save_authority",payload),
  verify_authority: (payload:Record<string,unknown>={}) => call("verify_authority",payload),
  list_legal_documents: (payload:Record<string,unknown>={}) => call("list_legal_documents",payload),
  save_legal_document_draft: (payload:Record<string,unknown>={}) => call("save_legal_document_draft",payload),
  approve_legal_document: (payload:Record<string,unknown>={}) => call("approve_legal_document",payload),
  create_legal_document_version: (payload:Record<string,unknown>={}) => call("create_legal_document_version",payload),
  export_legal_document: (payload:Record<string,unknown>={}) => call("export_legal_document",payload),
};
